<a href="https://colab.research.google.com/github/Luis505mk/Colab/blob/main/Escuela.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import sqlite3
import pandas as pd

# Conexión en memoria (se pierde al cerrar el notebook)
conn = sqlite3.connect(":memory:")
cur = conn.cursor() #objeto para ejecutar comandos de SQL

def query(sql, params=()):
    """Ejecuta un SELECT y devuelve un DataFrame para verlo bonito."""
    return pd.read_sql_query(sql, conn, params=params)

def run(sql, params=()):
    """Ejecuta INSERT/UPDATE/DELETE/DDL y hace commit."""
    cur.execute(sql, params)
    conn.commit()
    print("OK ->", sql.strip().splitlines()[0], "...")

Creamos la tabla llamada **alumnos**

In [20]:
#Creamos la tabla alumnos
cur.executescript('''
DROP TABLE IF EXISTS alumnos;

CREATE TABLE alumnos (
    id_alumno INTEGER PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    grado VARCHAR(10),
    edad INTEGER,
    promedio DECIMAL(4,2)
);
''')

conn.commit()
print("Tabla alumnos creada")

Tabla alumnos creada

Realizamos varios insert de **alumnos** y mostramos la tabla

In [21]:
#INSERT
run("""
INSERT INTO alumnos
VALUES (1, 'Juan Perez', '3A', 15, 8.5)
""")

run("""
INSERT INTO alumnos
VALUES (2, 'Ana Lopez', '5B', 17, 9.2)
""")

run("""
INSERT INTO alumnos
VALUES (3, 'Carlos Ruiz', '4A', 16, 8.8)
""")

conn.commit()

query("SELECT * FROM alumnos")

OK -> INSERT INTO alumnos ...
OK -> INSERT INTO alumnos ...
OK -> INSERT INTO alumnos ...

   id_alumno       nombre grado  edad  promedio
0          1   Juan Perez    3A    15       8.5
1          2    Ana Lopez    5B    17       9.2
2          3  Carlos Ruiz    4A    16       8.8

Realizamos un **UPDATE** al promedio de **Juan Perez** de **8.5** a **9.8**

In [22]:
#UPDATE
cur.execute("""
UPDATE alumnos
SET promedio = 9.8
WHERE nombre = 'Juan Perez'
""")

conn.commit()

query("SELECT * FROM alumnos")

   id_alumno       nombre grado  edad  promedio
0          1   Juan Perez    3A    15       9.8
1          2    Ana Lopez    5B    17       9.2
2          3  Carlos Ruiz    4A    16       8.8

Eliminamos de la tabla a **Carlos Ruiz** y mostramos la tabla

In [23]:
#DELETE
cur.execute("""
DELETE FROM alumnos
WHERE nombre = 'Carlos Ruiz'
""")

conn.commit()

query("SELECT * FROM alumnos")

   id_alumno      nombre grado  edad  promedio
0          1  Juan Perez    3A    15       9.8
1          2   Ana Lopez    5B    17       9.2