<a href="https://colab.research.google.com/github/Luis505mk/Colab/blob/main/Restaurante.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
import pandas as pd

# Conexión en memoria (se pierde al cerrar el notebook)
conn = sqlite3.connect(":memory:")
cur = conn.cursor() #objeto para ejecutar comandos de SQL

def query(sql, params=()):
    """Ejecuta un SELECT y devuelve un DataFrame para verlo bonito."""
    return pd.read_sql_query(sql, conn, params=params)

def run(sql, params=()):
    """Ejecuta INSERT/UPDATE/DELETE/DDL y hace commit."""
    cur.execute(sql, params)
    conn.commit()
    print("OK ->", sql.strip().splitlines()[0], "...")

Creamos la tabla llamada **comidas**

In [ ]:
cur.executescript('''
DROP TABLE IF EXISTS comidas;

CREATE TABLE comidas (
  id_Platillo INTEGER PRIMARY KEY,
  nombre varchar(50)  NOT NULL,
  categoria varchar(30),
  precio decimal(6,2),
  disponible boolean
);
''')
conn.commit()
print("Tabla creadas")

Tabla creadas

Realizamos dos inser uno de **Refresco** y **sopa**

In [ ]:
#insert:de refresco
run("""
INSERT INTO comidas (nombre, categoria, precio, disponible)
VALUES ('Refresco', 'Bebida', 25.00, 1)
""")

conn.commit()

OK -> INSERT INTO comidas (nombre, categoria, precio, disponible) ...

In [ ]:
#insert:de comida

run(""" INSERT INTO comidas ( nombre, categoria, precio ) VALUES

('Sopa', 'entrada', 100 );""")

query("select * from comidas")

OK -> INSERT INTO comidas ( nombre, categoria, precio ) VALUES ...

   id_Platillo    nombre categoria  precio  disponible
0            1  Refresco    Bebida      25         1.0
1            2      Sopa   entrada     100         NaN

Realizamos la actualizacion del precio de la **Sopa** con un **UPDATE**

In [ ]:
#update

cur.execute("""
UPDATE comidas
SET precio = 120
WHERE nombre = 'Sopa'
""")

conn.commit()

print("Precio actualizado")
query("SELECT * FROM comidas")

Precio actualizado

   id_Platillo    nombre categoria  precio  disponible
0            1  Refresco    Bebida      25         1.0
1            2      Sopa   entrada     120         NaN

Eliminamos un platillo con el **id 1**, correspondiente al **Refresco** y mostramos la tabla nuevamente

In [ ]:
#DELETE
cur.execute("""
DELETE FROM comidas
WHERE id_Platillo = 1
""")

conn.commit()

query("SELECT * FROM comidas")

   id_Platillo nombre categoria  precio disponible
0            2   Sopa   entrada     120       None