<a href="https://colab.research.google.com/github/Luis505mk/Colab/blob/main/Tienda_escolar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Conexión en memoria (se pierde al cerrar el notebook)
conn = sqlite3.connect(":memory:")
cur = conn.cursor() #objeto para ejecutar comandos de SQL

def query(sql, params=()):
    """Ejecuta un SELECT y devuelve un DataFrame para verlo bonito."""
    return pd.read_sql_query(sql, conn, params=params)

def run(sql, params=()):
    """Ejecuta INSERT/UPDATE/DELETE/DDL y hace commit."""
    cur.execute(sql, params)
    conn.commit()
    print("OK ->", sql.strip().splitlines()[0], "...")

In [4]:
#Creamos la tabla productos
cur.executescript('''
DROP TABLE IF EXISTS productos;

CREATE TABLE productos (
    id_producto INTEGER PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    tipo VARCHAR(30),
    precio DECIMAL(6,2),
    existencia INTEGER
);
''')

conn.commit()
print("Tabla productos creada")

Tabla productos creada

In [5]:
#INSERT

run("""
INSERT INTO productos
VALUES (1, 'Papas', 'Snack', 18.50, 20)
""")

run("""
INSERT INTO productos
VALUES (2, 'Agua', 'Bebida', 12.00, 30)
""")

run("""
INSERT INTO productos
VALUES (3, 'Galletas', 'Snack', 15.00, 25)
""")

conn.commit()

query("SELECT * FROM productos")

OK -> INSERT INTO productos ...
OK -> INSERT INTO productos ...
OK -> INSERT INTO productos ...

   id_producto    nombre    tipo  precio  existencia
0            1     Papas   Snack    18.5          20
1            2      Agua  Bebida    12.0          30
2            3  Galletas   Snack    15.0          25

In [6]:
#UPDATE
cur.execute("""
UPDATE productos
SET existencia = 50
WHERE nombre = 'Papas'
""")

conn.commit()

query("SELECT * FROM productos")

   id_producto    nombre    tipo  precio  existencia
0            1     Papas   Snack    18.5          50
1            2      Agua  Bebida    12.0          30
2            3  Galletas   Snack    15.0          25

In [7]:
#DELETE
cur.execute("""
DELETE FROM productos
WHERE nombre = 'Galletas'
""")

conn.commit()

query("SELECT * FROM productos")

   id_producto nombre    tipo  precio  existencia
0            1  Papas   Snack    18.5          50
1            2   Agua  Bebida    12.0          30